[[mold]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b4b241429de0ab6affab1a86b43231422602ffb9"
libc = "glibc"
os = "linux"

    [[mold.download]]
    sha256 = "2612b362a34d1faaa74fe7e847b64985f773072eeed21af8ce05ea0159545a18"
    url = "https://github.com/JuliaBinaryWrappers/mold_jll.jl/releases/download/mold-v1.2.0+0/mold.v1.2.0.aarch64-linux-gnu-cxx03.tar.gz"
[[mold]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "70554ca665475bbfd74325056d20ab9fdb62db48"
libc = "glibc"
os = "linux"

    [[mold.download]]
    sha256 = "95295fcf4ccfc83f32b6c88005714bf20bb8051c7c94b02e163c7d05da037b40"
    url = "https://github.com/JuliaBinaryWrappers/mold_jll.jl/releases/download/mold-v1.2.0+0/mold.v1.2.0.aarch64-linux-gnu-cxx11.tar.gz"
[[mold]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fb5f04bad0a9c0986f382f6f18b0b95509cfc8e9"
libc = "musl"
os = "linux"

    [[mold.download]]
    sha256 = "125178e50953f986e3aae8ca167d8e0aade0c588dd53ada5fe6745ab06d9fe12"
    url = "https://github.com/JuliaBinaryWrappers/mold_jll.jl/releases/download/mold-v1.2.0+0/mold.v1.2.0.aarch64-linux-musl-cxx03.tar.gz"
[[mold]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5d88517a8cc04bcac48bc3d24a2db3e1ad0ecd82"
libc = "musl"
os = "linux"

    [[mold.download]]
    sha256 = "e7d2536431bedcea69e524fbc17bef309aa403b68ed574ba9cb2eac270d38372"
    url = "https://github.com/JuliaBinaryWrappers/mold_jll.jl/releases/download/mold-v1.2.0+0/mold.v1.2.0.aarch64-linux-musl-cxx11.tar.gz"
[[mold]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "117c8f44510c67f95153488fe347a501baba632d"
libc = "glibc"
os = "linux"

    [[mold.download]]
    sha256 = "6a6c2e7973e5b1153a43a834dad442612e6f87bc96a3545540ef8c2d1df4cf95"
    url = "https://github.com/JuliaBinaryWrappers/mold_jll.jl/releases/download/mold-v1.2.0+0/mold.v1.2.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[mold]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "21e2ba9a79c8891c9dfae5da9abab697f9394e34"
libc = "glibc"
os = "linux"

    [[mold.download]]
    sha256 = "147b882f205b17b045dd837e39a9d3212d71a804456aaeaad4596b81720b326b"
    url = "https://github.com/JuliaBinaryWrappers/mold_jll.jl/releases/download/mold-v1.2.0+0/mold.v1.2.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[mold]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "40b4421078eaa6dafa4308f15af7f6512e8fad2d"
libc = "musl"
os = "linux"

    [[mold.download]]
    sha256 = "3a951210158bbf14ff8fd4fd06a13848775415f073809c2e7e1846b207818700"
    url = "https://github.com/JuliaBinaryWrappers/mold_jll.jl/releases/download/mold-v1.2.0+0/mold.v1.2.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[mold]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "52c0ec7e4c7109c81af157eac70f2ae92a901a7b"
libc = "musl"
os = "linux"

    [[mold.download]]
    sha256 = "3988dcadf415a54ae42aa8fbdb322fca1ba50528b5fc109e71a819018dc203c9"
    url = "https://github.com/JuliaBinaryWrappers/mold_jll.jl/releases/download/mold-v1.2.0+0/mold.v1.2.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[mold]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "35e350097ec3bcf530b7135d48606d17eb4f6800"
libc = "glibc"
os = "linux"

    [[mold.download]]
    sha256 = "8db474b0fa7f5e3df6a2ad154a8b7d2e46eb6b660d299973f4a1532667894e9d"
    url = "https://github.com/JuliaBinaryWrappers/mold_jll.jl/releases/download/mold-v1.2.0+0/mold.v1.2.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[mold]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "18c1069a93f964e3b438e33c4c0ce994fc7aefac"
libc = "glibc"
os = "linux"

    [[mold.download]]
    sha256 = "bf5f955b5814689a99410ab602c670a304da529922ef628e3f1899c3b1ea5281"
    url = "https://github.com/JuliaBinaryWrappers/mold_jll.jl/releases/download/mold-v1.2.0+0/mold.v1.2.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[mold]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d267db6d636c2a97f4e0566c8e04d7ba97bd5145"
libc = "musl"
os = "linux"

    [[mold.download]]
    sha256 = "73c74f059aab257798e5cbedff2cb8ba8660583bb510662cb1764173ed211dc4"
    url = "https://github.com/JuliaBinaryWrappers/mold_jll.jl/releases/download/mold-v1.2.0+0/mold.v1.2.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[mold]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9f7b19f05ffb500b802291acfce35550062b63bd"
libc = "musl"
os = "linux"

    [[mold.download]]
    sha256 = "d9bfead4a7051c5116e8e3231645fdf06e3b11c8a4158c9fb702eaab29e16ff5"
    url = "https://github.com/JuliaBinaryWrappers/mold_jll.jl/releases/download/mold-v1.2.0+0/mold.v1.2.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[mold]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "893040c2c71dd224712e29d6e3383a60ca02949a"
libc = "glibc"
os = "linux"

    [[mold.download]]
    sha256 = "f6ad9286552cb5f7517ae0a7dc03e0e3d928a7ca95a75a0e0fd9d36fb5e5109d"
    url = "https://github.com/JuliaBinaryWrappers/mold_jll.jl/releases/download/mold-v1.2.0+0/mold.v1.2.0.i686-linux-gnu-cxx03.tar.gz"
[[mold]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "46ba2b7f70b7c6e6e99f819af6afb34ad60179cf"
libc = "glibc"
os = "linux"

    [[mold.download]]
    sha256 = "550efb5f8874b5b89a03a5e35159ac060bceaae87903fce53038a3c6fe89cf7b"
    url = "https://github.com/JuliaBinaryWrappers/mold_jll.jl/releases/download/mold-v1.2.0+0/mold.v1.2.0.i686-linux-gnu-cxx11.tar.gz"
[[mold]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "80535b245a1ee8a8d16c22f2b29a3913adb3d85a"
libc = "musl"
os = "linux"

    [[mold.download]]
    sha256 = "a57cbc3a1c81d70f978f1e390d0fb63b003b822a8c7b63b35511033b73ab4502"
    url = "https://github.com/JuliaBinaryWrappers/mold_jll.jl/releases/download/mold-v1.2.0+0/mold.v1.2.0.i686-linux-musl-cxx03.tar.gz"
[[mold]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ebafd68d4064c0e7043426abbaf83a88c7c342e6"
libc = "musl"
os = "linux"

    [[mold.download]]
    sha256 = "1f142a3ecfeb92042d22897de5b3bc728eccdc70d2e2c9a0a889d1c23e1aa51d"
    url = "https://github.com/JuliaBinaryWrappers/mold_jll.jl/releases/download/mold-v1.2.0+0/mold.v1.2.0.i686-linux-musl-cxx11.tar.gz"
[[mold]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "30c8e883b499e24da0961ecfadac407ccb389972"
libc = "glibc"
os = "linux"

    [[mold.download]]
    sha256 = "bd39ba4649fd364bd074ec2dcd536fa6b6bf968f27bf143c41500deca46d2796"
    url = "https://github.com/JuliaBinaryWrappers/mold_jll.jl/releases/download/mold-v1.2.0+0/mold.v1.2.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[mold]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1bc540d0c1936655214da0f1f92ccc9b0d18ef7c"
libc = "glibc"
os = "linux"

    [[mold.download]]
    sha256 = "210cab6e594015a6466a84f073abaf0934d6c2e41b6977f800a0a71f863f458d"
    url = "https://github.com/JuliaBinaryWrappers/mold_jll.jl/releases/download/mold-v1.2.0+0/mold.v1.2.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[mold]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "422ac794f052afb97511c1d6690ec38d5e018f4c"
libc = "glibc"
os = "linux"

    [[mold.download]]
    sha256 = "0dbfefdfaef089d3ac1ac43552c334d400ac621edce1012671b6fadc725a60cb"
    url = "https://github.com/JuliaBinaryWrappers/mold_jll.jl/releases/download/mold-v1.2.0+0/mold.v1.2.0.x86_64-linux-gnu-cxx03.tar.gz"
[[mold]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e26c527e07e99b1e6216e959bce35659871bdad8"
libc = "glibc"
os = "linux"

    [[mold.download]]
    sha256 = "66a7a8fd6bd11a11bb91e2fe45c8e3f1246e3845e384731e4c6f0dc0bf9db02a"
    url = "https://github.com/JuliaBinaryWrappers/mold_jll.jl/releases/download/mold-v1.2.0+0/mold.v1.2.0.x86_64-linux-gnu-cxx11.tar.gz"
[[mold]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "98904232a8cc4841705add22aaeb24a1d3eb10e3"
libc = "musl"
os = "linux"

    [[mold.download]]
    sha256 = "b013efe1d0bd84235dea825a891c618ac726b7f4ac216ae4722b92e188a96b12"
    url = "https://github.com/JuliaBinaryWrappers/mold_jll.jl/releases/download/mold-v1.2.0+0/mold.v1.2.0.x86_64-linux-musl-cxx03.tar.gz"
[[mold]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9c3669d082ba223d027d4a21f8478617b5416962"
libc = "musl"
os = "linux"

    [[mold.download]]
    sha256 = "1728a28a59064a206891608baf3b4d888f397a58c5fca2f3dd4ac04f73d5bc85"
    url = "https://github.com/JuliaBinaryWrappers/mold_jll.jl/releases/download/mold-v1.2.0+0/mold.v1.2.0.x86_64-linux-musl-cxx11.tar.gz"
